contact/urls.py
from django.urls import path
from contact import views

app_name ="contact"

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('search/', views.search,name="search"),

    # CRUD
    path('contact/create', views.create,name="create"),
    path('contact/<int:contact_id>/detail', views.contact,name="contact"),
    path('contact/<int:contact_id>/update', views.update,name="update"),
    path('contact/<int:contact_id>/delete', views.delete,name="delete"),



    path('user/register', views.register,name="register"),
    path('user/login', views.login_view,name="login"),
    path('user/logout', views.logout_view,name="logout"),
    path('user/update', views.user_update,name="user_update"),
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

import contact.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(contact.urls)),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.MEDIA_URL)

base/global/templates/partials/_head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title> {{site_title}}  Agenda </title>
<link rel="stylesheet" href=" {% static 'global/css/styles.css' %} ">

base/global/templates/partials/_header.html
<header class="header">
    <h1 class="header-heading">
        <a href="{% url "contact:index" %}" class="header-link">Agenda</a>
        </h1>
    <nav class="menu">
        <ul class="menu-list">
            {% if user.is_authenticated %}
                <li class="menu-item"><a href="{% url "contact:create" %}" class="menu-link">Create</a></li>
                <li class="menu-item"><a href="{% url "contact:user_update" %}" class="menu-link">Profire</a></li>
                <li class="menu-item"><a href="{% url "contact:logout" %}" class="menu-link">Logout</a></li>

            {% else %}

                <li class="menu-item"><a href="{% url "contact:login" %}" class="menu-link">Login</a></li>
                <li class="menu-item"><a href="{% url "contact:register" %}" class="menu-link">Register</a></li>
            
            {% endif %}
     
        </ul>
    </nav>
    <div class="search">
        <form action="{% url "contact:search" %}" method="GET" >
            <input 
                type="text" 
                class="search-input" 
                placeholder="Search" 
                id="search" 
                name="q"
                value="{{search_value}}"
            >
        </form>
    </div>
    

</header>

base/global/templates/partials/_messages.html
{% if messages %}
    {% for message in messages  %}
        <div class="message {{message.tags}}" >
            {{message}}
            {{message.tags}}
        </div>
    {% endfor %}
{% endif %}

base/global/templates/partials/_pagination.html
{% if page_obj %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1&q={{search_value}}">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}&q={{search_value}}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&q={{search_value}}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}&q={{search_value}}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}