contact/urls.py
from django.urls import path
from contact import views

app_name ="contact"

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('search/', views.search,name="search"),

    # CRUD
    path('contact/create', views.create,name="create"),
    path('contact/<int:contact_id>/detail', views.contact,name="contact"),
    path('contact/<int:contact_id>/update', views.update,name="update"),
    path('contact/<int:contact_id>/delete', views.delete,name="delete"),



    path('user/register', views.register,name="register"),
    path('user/login', views.login_view,name="login"),
    path('user/logout', views.logout_view,name="logout"),
    path('user/update', views.user_update,name="user_update"),
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

import contact.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(contact.urls)),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.MEDIA_URL)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):

    class Meta:

        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class Contact(models.Model):

    first_name = models.CharField( max_length=50)
    last_name = models.CharField( max_length=50,blank=True)
    phone = models.CharField(max_length=14,blank=True)
    email = models.EmailField(max_length=250,blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(max_length=500,blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True,upload_to='pictures/%Y/%m/%d')
    category = models.ForeignKey(Category,
                                    on_delete=models.SET_NULL,
                                    blank=True, 
                                    null=True)
    onwer = models.ForeignKey(User,
                                    on_delete=models.SET_NULL,
                                    blank=True, 
                                    null=True)
    
    def __str__(self) -> str:
        return f'{self.first_name}  {self.last_name}'
    

contact/forms.py
from typing import Any, Mapping
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from contact.models import Contact
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation
from django.contrib.auth.models import User


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'Rebeca'}),
        label='Primeiro Nome',
        help_text='Digite Seu primeiro nome'
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'Lohane'}),
        label='Sobrenome',
        
    )

    phone = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'75988770024'}),
        label='Telefone',
        
    )

    email = forms.CharField(
        widget=forms.EmailInput(attrs={'placeholder':'rebecaloh@email.com'}),
        label='Email',
        
    )
    picture = forms.ImageField(
        widget=forms.FileInput(attrs={'accept':'image/*'}),
        required=False
    )


    # ATUALIZANDO O WIDGET
    # def __init__(self,*args, **kwargs):
    #     super().__init__(*args, **kwargs)

    #     self.fields['first_name'].widget.attrs.update({
    #         'placeholder':'Perla Pepa'
    #     })

    class Meta:
        model = Contact
        fields = ('first_name','last_name','phone','email','description','category','picture',)
        # CRIANDO UM NOVO widgets PARA O CAMPO
        # widgets= {'first_name': forms.TextInput(
        #     attrs={'placeholder':'Perla'}
        # )}

    def clean(self):

        cleaned_data = self.cleaned_data

        # self.add_error(
        #     None,
        #     ValidationError(
        #         'Mensagem error',
        #         code ='invalid'

        #     )
        # )
        return super().clean()
        
class RegisterForm(UserCreationForm):

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'Rebeca'}),
        label='Primeiro Nome',
        help_text='Digite Seu primeiro nome',
        required=True,
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'Lohane'}),
        label='Primeiro Nome',
        help_text='Digite Seu primeiro nome'
    )

    
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'placeholder':'rebecaloh@email.com'}),
        label='Email',
        
    )

    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'rebloh'}),
        label='Login',
        
    )
    class Meta:
        model = User
        fields=('first_name','last_name','email',
                'username','password1','password2')
        

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error('email',
                           ValidationError('Email já cadastrado',code='invalid'))
            return email
        return email
            
class RegisteupdateForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'Rebeca'}),
        label='Primeiro Nome',
        help_text='Digite Seu primeiro nome',
        required=True,
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'Lohane'}),
        label='Primeiro Nome',
        help_text='Digite Seu primeiro nome'
    )

    
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'placeholder':'rebecaloh@email.com'}),
        label='Email',
        
    )

    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'rebloh'}),
        label='Login',
        
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget= forms.PasswordInput(attrs={"autocomplete":"new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
                                    
    )
    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget= forms.PasswordInput(attrs={"autocomplete":"new-password"}),
        help_text="Use the same password as before.",
        required=False,
                                    
    )
    class Meta:
        model = User
        fields=('first_name','last_name','email',
                'username',)


    
    def save(self,commit = True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)

        password = cleaned_data.get('password1')
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user

    def clean(self):
        cleaned_data = self.cleaned_data
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error('password2',
                               ValidationError('Valores divergentes'))


        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email
        if email != current_email:
            if User.objects.filter(email=email).exists():
                self.add_error('email',
                            ValidationError('Email já cadastrado',code='invalid'))
        return email
        

contact/views.py
from django.shortcuts import render

#app_name = 'contact'

def index(request):
    return render(request,'contact/index.html')

contact/views/contact_create.py
from django.shortcuts import render,redirect,get_object_or_404
from contact.forms import ContactForm
from django.urls import reverse
from contact.models import Contact



app_name = 'contact'

def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST,request.FILES)

        context = {
            'form': form,
            'form_action':form_action,
            }

        if form.is_valid():
            contact = form.save()

            return redirect('contact:update',contact_id=contact.pk)


        return render(request,'contact/create.html',context)
    
    context = {
        'form': ContactForm(),
        'form_action':form_action,
        }

    return render(request,'contact/create.html',context)


def update(request, contact_id):
    
    contact = get_object_or_404(
        Contact,
        pk=contact_id,
        show= True
    )
    form_action = reverse('contact:update',args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST,request.FILES,instance=contact)

        context = {
        'form': form,
        'form_action':form_action,
            }
        
        if form.is_valid():
            form.save()
            contact = form.save()
            return  redirect('contact:update',contact_id=contact.pk)

     
    
        return render(request,'contact/create.html',context)
 
    context = {
        'form': ContactForm(instance=contact),
        'form_action':form_action
    }

    return render(request,'contact/create.html',context)

def delete(request, contact_id):
    
    contact = get_object_or_404(
        Contact,
        pk=contact_id,
        show= True
    )
    confirmation = request.POST.get('confirmation','no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
        
    context = {
        'contact':contact,
        'confirmation':confirmation
    }
    return render(request,'contact/contact.html',context)

contact/views/contact_forms.py
from django.shortcuts import render,redirect,get_object_or_404
from contact.forms import ContactForm
from django.urls import reverse
from contact.models import Contact
from django.contrib.auth.decorators import login_required



app_name = 'contact'

@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST,request.FILES)

        context = {
            'form': form,
            'form_action':form_action,
            }

        if form.is_valid():
            contact = form.save(commit=False)
            contact.onwer = request.user
            contact.save()

            return redirect('contact:update',contact_id=contact.pk)


        return render(request,'contact/create.html',context)
    
    context = {
        'form': ContactForm(),
        'form_action':form_action,
        }

    return render(request,'contact/create.html',context)

@login_required(login_url='contact:login')
def update(request, contact_id):
    
    contact = get_object_or_404(
        Contact,
        pk=contact_id,
        show= True,
        onwer = request.user,
    )
    form_action = reverse('contact:update',args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST,request.FILES,instance=contact)

        context = {
        'form': form,
        'form_action':form_action,
            }
        
        if form.is_valid():
            form.save()
            contact = form.save()
            return  redirect('contact:update',contact_id=contact.pk)

     
    
        return render(request,'contact/create.html',context)
 
    context = {
        'form': ContactForm(instance=contact),
        'form_action':form_action
    }

    return render(request,'contact/create.html',context)

@login_required(login_url='contact:login')
def delete(request, contact_id):
    
    contact = get_object_or_404(
        Contact,
        pk=contact_id,
        show= True,
        onwer = request.user,
    )
    confirmation = request.POST.get('confirmation','no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
        
    context = {
        'contact':contact,
        'confirmation':confirmation
    }
    return render(request,'contact/contact.html',context)

contact/views/contact_views.py
from django.shortcuts import render,get_object_or_404,redirect
from contact.models import Contact
from django.db.models import Q
from django.http import Http404
from django.db.models import Max
from django.core.paginator import Paginator


#app_name = 'contact'

def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')

    paginator = Paginator(contacts, 10)  
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
            'page_obj':page_obj,
            'site_title':'Contatos -'}

    return render(request,'contact/index.html',context)




def contact(request,contact_id):
    max_id = Contact.objects.aggregate(Max('id'))['id__max']
    
    #if (contact_id is None) or ( contact_id > max_id):
    #    raise Http404('Concato não existe')
    single_contact = get_object_or_404(Contact,pk=contact_id,show=True)
    
    contact_name = f'{single_contact.first_name} {single_contact.last_name} - '
    
    context ={
        'contact':single_contact,
        'site_title':contact_name
    
    }

    return render(request,'contact/contact.html',context)



def search(request):
    search_value = request.GET.get('q','').strip()
    if search_value == '':
        return redirect('contact:index')
    
    contacts = Contact.objects.filter(show=True)\
                                .filter(
                                    Q(first_name__icontains=search_value) |
                                    Q(last_name__icontains=search_value) |
                                    Q(phone__icontains=search_value) |
                                    Q(email__icontains=search_value)
                                    )\
                                .order_by('-id')
    paginator = Paginator(contacts, 10)  
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
            'page_obj':page_obj,
            'site_title':'Contatos -',
            'search_value':search_value
            }

    return render(request,'contact/index.html',context)

contact/views/user_form.py
from django.shortcuts import render,redirect
from django.contrib import messages,auth
from contact.forms import RegisterForm
from contact.forms import RegisteupdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

def register(request):
        form = RegisterForm()

        # messages.info(request,'Mensagem Informativa')
        # messages.success(request,'Mensagem Sucesso!')
        # messages.error(request,'Mensagem Erro!')
        # messages.warning(request,'Mensagem Alerta!')

        if request.method == 'POST':
                form = RegisterForm(request.POST)
                if form.is_valid():
                        form.save()
                        messages.success(request,'Usuário cadastrado !')
                        return redirect('contact:index')

        
                



        context = {
            'form':form
            }

        return render(request,'contact/register.html',context)

def login_view(request):
        form = AuthenticationForm()

        if request.method == 'POST':
                form = AuthenticationForm(request,data=request.POST)
                if form.is_valid():
                        user = form.get_user()
                        auth.login(request,user)
                        messages.success(request,'Usuário logado!')
                        return redirect('contact:index')
                messages.error(request,'Dados não são válidos')
        context = {'form':form}
        return render(request,'contact/login.html',context)



@login_required(login_url='concact:login')
def user_update(request):
        if request.user.is_authenticated:
                form = RegisteupdateForm(instance=request.user)
                context ={'form':form}
                if request.method == 'POST':
                        form = RegisteupdateForm(data=request.POST,instance=request.user)
                        if form.is_valid():
                                form.save()
                                context ={'form':form}
                                return redirect('contact:user_update')
                        
                

                
                return render(request,'contact/user_update.html',context)
        else:
                messages.error(request,'Não existe usuário logado')
                return redirect('contact:login')
        
@login_required(login_url='concact:login')
def logout_view(request):
        auth.logout(request)
        return redirect('contact:login')

contact/templates/contact/contact.html
{% extends "global/templates/index.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>
        <p><b>ID: </b>{{contact.id}}</p>
        <p><b>PHONE: </b>{{contact.phone}}</p>
        <p><b>EMAIL: </b>{{contact.email}}</p>
        <p><b>DATE CREATED: </b>{{contact.created_date}}</p>
        <p><b>DESCRIPTION: </b>{{contact.description}}</p>
        <p><b>CATEGORY: </b>{{contact.category.name}}</p>
        
        {% if contact.picture  %}
            <p>
                <img src="{{contact.picture.url}}" alt=" {{contact.first_name}} {{contact.last_name}}">
            </p>
        {% endif %}
        {% if user == contact.owner %}
            <div class="contact-links">
                <a class="btn btn-link" href="{% url "contact:update" contact.id %}">Update</a>
                
                <form action="{% url "contact:delete" contact.id %}" method="post">
                    {% csrf_token %}
                    {% if confirmation == 'no' %}
                        <input type="hidden" name="confirmation" value="yes">
                        <button class="btn btn-link btn-delete" type="submit">Confirm?</button>
                    {% else %}
                        <button class="btn btn-link btn-delete" type="submit">Delete</button>
                    {% endif %}
                </form>
                
            </div>
        {% endif %}
    </div>

{% endblock content %}
    

contact/templates/contact/create.html
{% extends "global/templates/index.html" %}


{% block content %}
    <h1>Create contact</h1>
    <div class="form-wrapper">
        <h2>Contact</h2>
        <form action="{{form_action}}" method="POST" enctype="multipart/form-data">
            <p>Acao:{{form_action}}</p>
            {% csrf_token %}
            <div class="form-content">
                {% for field in form  %}
                <div class="form-group">
                    <label for="field.id_for_label" >{{field.label}}</label>
                    {{field}}
                    {{field.errors}}
                    {% if field.help_text %}
                        <p class="help-text">
                            {{field.help_text}}
                        </p>
                    {% endif %}
                </div>
                {% endfor %}
            </div>

            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            <p>{{form.non_field_errors }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Send</button>
                </div>
            </div>
        </form>
    </div>
    

{% endblock content %}

contact/templates/contact/index.html
{% extends "global/templates/index.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                contacts
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">FIRST NAME</th>
                    <th class="table-header">LAST NAME</th>
                    <th class="table-header">PHONE</th>
                    <th class="table-header">EMAIL</th>
                </tr>
            </thead>

            <TBOdy>
                {% for contact in page_obj  %}
                    <tr classe="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url "contact:contact" contact.id %}" >
                                {{contact.id}}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{contact.first_name}}
                        </td>
                        <td class="table-cel">
                            {{contact.last_name}}
                        </td>
                        <td class="table-cel">
                            {{contact.phone}}
                        </td>
                        <td class="table-cel">
                            {{contact.email}}
                        </td>
                    </tr>
                {% endfor %}
            </TBOdy>

        </table>


    </div>

{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Contato não encontrado
    </h1>

</div>

{% endif %}   
{% endblock content %}

    

contact/templates/contact/login.html
{% extends "global/templates/index.html" %}


{% block content %}
    <div class="form-wrapper">
        <h2>Login</h2>
        {% if user.is_authenticated %}
            <p>Já logado, sair <a href="{% url "contact:logout" %}">Aqui</a> </p>
        {% else %}
            {% include "contact/partial/_form-user.html" %}
        {% endif %}
        
    </div>
    

{% endblock content %}

contact/templates/contact/register.html
{% extends "global/templates/index.html" %}


{% block content %}
    <div class="form-wrapper">
        <h2>Contact</h2>
        <form action="{{form_action}}" method="POST" >
            {% csrf_token %}
            <div class="form-content">
                {% for field in form  %}
                    <div class="form-group">
                        <label for="field.id_for_label" >{{field.label}}</label>
                        {{field}}
                        {{field.errors}}
                        {% if field.help_text %}
                            <p class="help-text">
                                {{field.help_text}}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>

            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            <p>{{form.non_field_errors }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Send</button>
                </div>
            </div>
        </form>
    </div>
    

{% endblock content %}

contact/templates/contact/user_update.html
{% extends "global/templates/index.html" %}


{% block content %}
    <div class="form-wrapper">
        <h2>Update User</h2>
        {% include "contact/partial/_form-user.html" %}
    </div>
    

{% endblock content %}